<a href="https://colab.research.google.com/github/jayac251/Machine_Learning/blob/main/Pandas_Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

1. Create the following Series and do the specified operations:

a) EngAlph, having 26 elements with the alphabets as values and default index values.

b) Vowels, having 5 elements with index labels ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’ and all the five values set to zero. Check if it is an empty series.

c) Friends, from a dictionary having roll numbers of five of your friends as data and their first name as keys.

d) MTseries, an empty Series. Check if it is an empty
series.

e) MonthDays, from a numpy array having the number of days in the 12 months of a year. The labels should be the month numbers from 1 to 12.

In [167]:
import string

# a) EngAlph, having 26 elements with the alphabets as values and default index values.
Alph = list(string.ascii_lowercase)

engAlph = pd.Series(Alph)

print('\n',engAlph)

# b) Vowels, having 5 elements with index labels ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’ and all the five values set to zero. Check if it is an empty series.
vowels = pd.Series(0, index = ['a','e','i','o','u'])
print('\n',vowels)
print('\n',vowels.empty)

# c) Friends, from a dictionary having roll numbers of five of your friends as data and their first name as keys.

friendDict = {'Anu':1111,
              'Banu':1112,
              'Chinu':1113,
              'Dinu':1114,
              'Finu':1115}
friends=pd.Series(friendDict)
print('\n',friends)     

# d) MTseries, an empty Series. Check if it is an empty series.

mtSeries = pd.Series()
print('\n',mtSeries.empty)

# e) MonthDays, from a numpy array having the number of days in the 12 months of a year. The labels should be the month numbers from 1 to 12.

days = np.array([31,30])

monthDays = pd.Series(np.tile(days,6),index = (np.arange(1,13)))

print(monthDays)


 0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

 a    0
e    0
i    0
o    0
u    0
dtype: int64

 False

 Anu      1111
Banu     1112
Chinu    1113
Dinu     1114
Finu     1115
dtype: int64

 True
1     31
2     30
3     31
4     30
5     31
6     30
7     31
8     30
9     31
10    30
11    31
12    30
dtype: int64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.


Using the Series created in Question 1, write commands for the following:

a) Set all the values of Vowels to 10 and display the Series.

b) Divide all values of Vowels by 2 and display the Series.

c) Create another series Vowels1 having 5 elements with index labels ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’ having values [2,5,6,3,8] respectively.

d) Add Vowels and Vowels1 and assign the result to Vowels3.

e) Subtract, Multiply and Divide Vowels by Vowels1.

f) Alter the labels of Vowels1 to [‘A’, ‘E’, ‘I’, ‘O’, ‘U’].

In [171]:
# a) Set all the values of Vowels to 10 and display the Series.
vowels = pd.Series(0, index = ['a','e','i','o','u'])
print(vowels)
vowels = vowels.replace(0,10)
print('\n',vowels)

# Other Method 
vowels.loc['a':'u']=10
print(vowels)

#Other Method 
vowels.iloc[0:5]=10
print(vowels)

# b) Divide all values of Vowels by 2 and display the Series.

vowels = vowels / 2
print('\n',vowels)

# c) Create another series Vowels1 having 5 elements with index labels ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’ having values [2,5,6,3,8] respectively.

vowels1 = pd.Series([2,5,6,3,8], index = ['a','e','i','o','u'])
print('\n',vowels1)


# d) Add Vowels and Vowels1 and assign the result to Vowels3.

vowels3 = vowels + vowels1
print('\n',vowels3)

# e) Subtract, Multiply and Divide Vowels by Vowels1.

vowels4 = vowels - vowels1
vowels5 = vowels * vowels1
vowels6 = vowels / vowels1

print('\n',vowels4)
print('\n',vowels5)
print('\n',vowels6)

# f) Alter the labels of Vowels1 to [‘A’, ‘E’, ‘I’, ‘O’, ‘U’].

print('\nBEFORE ALTER\n',vowels1)
vowels1.index=['A', 'E', 'I', 'O', 'U']
print('\nAFTER ALTER\n',vowels1)


a    0
e    0
i    0
o    0
u    0
dtype: int64

 a    10
e    10
i    10
o    10
u    10
dtype: int64
a    10
e    10
i    10
o    10
u    10
dtype: int64
a    10
e    10
i    10
o    10
u    10
dtype: int64

 a    5.0
e    5.0
i    5.0
o    5.0
u    5.0
dtype: float64

 a    2
e    5
i    6
o    3
u    8
dtype: int64

 a     7.0
e    10.0
i    11.0
o     8.0
u    13.0
dtype: float64

 a    3.0
e    0.0
i   -1.0
o    2.0
u   -3.0
dtype: float64

 a    10.0
e    25.0
i    30.0
o    15.0
u    40.0
dtype: float64

 a    2.500000
e    1.000000
i    0.833333
o    1.666667
u    0.625000
dtype: float64

BEFORE ALTER
 a    2
e    5
i    6
o    3
u    8
dtype: int64

AFTER ALTER
 A    2
E    5
I    6
O    3
U    8
dtype: int64


Using the Series created in Question 1, write commands for the following:

a) Find the dimensions, size and values of the Series EngAlph, Vowels, Friends, MTseries, MonthDays.

b) Rename the Series MTseries as SeriesEmpty.

c) Name the index of the Series MonthDays as monthno and that of Series Friends as Fname.

d) Display the 3rd and 2nd value of the Series Notes Friends, in that order.

e) Display the alphabets ‘e’ to ‘p’ from the Series EngAlph.

f) Display the first 10 values in the Series EngAlph. 

g) Display the last 10 values in the Series EngAlph.

h) Display the MTseries.

In [172]:
# a) Find the dimensions, size and values of the Series EngAlph, Vowels, Friends, MTseries, MonthDays.

getList = [engAlph,vowels,friends,mtSeries,monthDays]

for j in getList:
  print(j.ndim)
  print(j.shape)
  print(j.size)
  print(j.values)
  print('\n')

# b) Rename the Series MTseries as SeriesEmpty.

mtSeries.name = 'MTseries'
print(mtSeries.name)

mtSeries = mtSeries.rename('SeriesEmpty')
print(mtSeries.name)

#c) Name the index of the Series MonthDays as monthno and that of Series Friends as Fname.

monthDays.index.name = 'monthno'
friends.index.name = 'Fname'

print('\n\n', monthDays)

print('\n\n', friends)


1
(26,)
26
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


1
(5,)
5
[5. 5. 5. 5. 5.]


1
(5,)
5
[1111 1112 1113 1114 1115]


1
(0,)
0
[]


1
(12,)
12
[31 30 31 30 31 30 31 30 31 30 31 30]


MTseries
SeriesEmpty


 monthno
1     31
2     30
3     31
4     30
5     31
6     30
7     31
8     30
9     31
10    30
11    31
12    30
dtype: int64


 Fname
Anu      1111
Banu     1112
Chinu    1113
Dinu     1114
Finu     1115
dtype: int64


In [ ]:
# d) Display the 3rd and 2nd value of the Series Friends, in that order.
print(friends)
print('\n',friends[2:0:-1])

#e) Display the alphabets ‘e’ to ‘p’ from the Series EngAlph.
print('\n',engAlph)
print('\n',engAlph[4:16])

#f) Display the first 10 values in the Series EngAlph.
print('\n',engAlph.head(10))

#g) Display the last 10 values in the Series EngAlph.
print('\n',engAlph.tail(10))

#h) Display the MTseries.
print('\n\n',mtSeries)

Fname
Anu      1111
Banu     1112
Chinu    1113
Dinu     1114
Finu     1115
dtype: int64

 Fname
Chinu    1113
Banu     1112
dtype: int64

 0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

 4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
dtype: object

 0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object

 16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


 Series([], Name: SeriesEmpty, dtype: float64)


Using the Series created in Question 1, write commands for the following:

a) Display the names of the months 3 through 7 from the Series MonthDays.

b) Display the Series MonthDays in reverse order

In [177]:
# a) Display the names of the months 3 through 7 from the Series MonthDays.
#MonthDays
MonthDays=np.array([31,28,31,30,31,30,31,31,30,31,30,31])
month=pd.Series(MonthDays,index=np.arange(1,13))
month=pd.Series(MonthDays,index=["Jan","Feb","Mar","Apr","May","June",
                         "July","Aug","Sept","Oct","Nov","Dec"])
#Method 1
print('\n',month.iloc[2:7])

#Method 2
print('\n',month.loc['Mar':'July'])

#Method 3
print('\n',month['Mar':'July'])

# b) Display the Series MonthDays in reverse order
#Method 1
print(month[::-1])

#Method 2
print(month.iloc[::-1])

#Method 3
print(month.loc["Dec":"Jan":-1])


 Mar     31
Apr     30
May     31
June    30
July    31
dtype: int64

 Mar     31
Apr     30
May     31
June    30
July    31
dtype: int64

 Mar     31
Apr     30
May     31
June    30
July    31
dtype: int64
Dec     31
Nov     30
Oct     31
Sept    30
Aug     31
July    31
June    30
May     31
Apr     30
Mar     31
Feb     28
Jan     31
dtype: int64
Dec     31
Nov     30
Oct     31
Sept    30
Aug     31
July    31
June    30
May     31
Apr     30
Mar     31
Feb     28
Jan     31
dtype: int64
Dec     31
Nov     30
Oct     31
Sept    30
Aug     31
July    31
June    30
May     31
Apr     30
Mar     31
Feb     28
Jan     31
dtype: int64


Create the following DataFrame Sales containing year wise sales figures for five sales persons in INR.

Use the years as column labels, and sales person names as row labels.

2014 2015 2016 2017

Madhu 100.5 12000 20000 50000

Kusum 150.8 18000 50000 60000

Kinshuk 200.9 22000 70000 70000

Ankit 30000 30000 100000 80000

Shruti 40000 45000 125000 90000

In [215]:
salesDict = {2014:[100.5,150.8,200.9,30000,4000],
     2015:[12000,18000,22000,30000,45000],
     2016:[20000,50000,70000,10000,125000],
     2017:[50000,60000,70000,80000,90000]}

sales= pd.DataFrame(salesDict,index=['Madhu',"Kusum","Kinshuk","Ankit","Shruti"])

sales

2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000   10000  80000
Shruti    4000.0  45000  125000  90000

In [180]:
#a) Display the row labels of Sales.
print(sales.index)

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')


In [183]:
#b) Display the column labels of Sales.
print(sales.columns)

Index([2014, 2015, 2016, 2017, '2018'], dtype='object')


In [184]:
#c) Display the data types of each column of Sales.
print(sales.dtypes)

2014    float64
2015      int64
2016      int64
2017      int64
2018    float64
dtype: object


In [185]:
#d) Display the dimensions, shape, size and values of Sales.
print(sales.ndim,'\n',sales.shape,'\n',sales.size,'\n',sales.values)


2 
 (5, 5) 
 25 
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04 1.600e+05]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04 1.100e+05]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04 5.000e+05]
 [3.000e+04 3.000e+04 1.000e+04 8.000e+04 3.400e+05]
 [4.000e+03 4.500e+04 1.250e+05 9.000e+04 9.000e+05]]


In [186]:
#e) Display the last two rows of Sales.
print(sales.tail(2))

#f) Display the first two columns of Sales
print('\n\n',sales.head(2))



           2014   2015    2016   2017      2018
Ankit   30000.0  30000   10000  80000  340000.0
Shruti   4000.0  45000  125000  90000  900000.0


         2014   2015   2016   2017      2018
Madhu  100.5  12000  20000  50000  160000.0
Kusum  150.8  18000  50000  60000  110000.0


g) Create a dictionary using the following data. Use this dictionary to create a DataFrame Sales2.

      |2018|
Madhu |160000|

Kusum 110000

Kinshuk 500000

Ankit 340000

Shruti 900000

In [187]:
salesDict2 = {'2018':pd.Series([160000,110000,500000,340000,900000],index=['Madhu','Kusum','Kinshuk','Ankit','Shruti'])}

sales2 = pd.DataFrame(salesDict2)
sales2


2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000

In [188]:
#h) Check if Sales2 is empty or it contains data.

print(sales2.empty)

False


In [189]:
# a) Append the DataFrame Sales2 to the DataFrame Sales.

sales3 = sales.append(sales2)
print(sales3)





            2014     2015      2016     2017      2018
Madhu      100.5  12000.0   20000.0  50000.0  160000.0
Kusum      150.8  18000.0   50000.0  60000.0  110000.0
Kinshuk    200.9  22000.0   70000.0  70000.0  500000.0
Ankit    30000.0  30000.0   10000.0  80000.0  340000.0
Shruti    4000.0  45000.0  125000.0  90000.0  900000.0
Madhu        NaN      NaN       NaN      NaN  160000.0
Kusum        NaN      NaN       NaN      NaN  110000.0
Kinshuk      NaN      NaN       NaN      NaN  500000.0
Ankit        NaN      NaN       NaN      NaN  340000.0
Shruti       NaN      NaN       NaN      NaN  900000.0


In [190]:
# b) Change the DataFrame Sales such that it becomes its transpose.

sales3 = sales.T
print(sales3)


         Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0    4000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0   10000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0


In [204]:
# c) Display the sales made by all sales persons in the year 2017.
sales3 = sales
sales3[2017]


Madhu      50000
Kusum      60000
Kinshuk    70000
Ankit      80000
Shruti     90000
Name: 2017, dtype: int64

In [216]:
# d) Display the sales made by Madhu and Ankit in the year 2017 and 2018.

sales4 = sales
sales4[2018] = [160000.0,110000.0,500000.0,340000.0,900000.0]
print(sales4)
print('\n\n',sales4[2018])

#other method
print(sales4.loc[sales4.index.isin(["Madhu","Ankit"]),[2017,2018]])




            2014   2015    2016   2017      2018
Madhu      100.5  12000   20000  50000  160000.0
Kusum      150.8  18000   50000  60000  110000.0
Kinshuk    200.9  22000   70000  70000  500000.0
Ankit    30000.0  30000   10000  80000  340000.0
Shruti    4000.0  45000  125000  90000  900000.0


 Madhu      160000.0
Kusum      110000.0
Kinshuk    500000.0
Ankit      340000.0
Shruti     900000.0
Name: 2018, dtype: float64
        2017      2018
Madhu  50000  160000.0
Ankit  80000  340000.0


In [211]:
# e) Display the sales made by Shruti 2016.
print(sales4.loc[sales4.index=='Shruti',2016])

Shruti    125000
Name: 2016, dtype: int64


In [217]:
# f) Add data to Sales for salesman Sumeet where the sales made are [196.2, 37800, 52000, 78438, 38852] in the years [2014, 2015, 2016, 2017, 2018] respectively.
sales4.loc["Sumeet"] = [196.2, 37800, 52000, 78438, 38852]
print(sales4)

            2014     2015      2016     2017      2018
Madhu      100.5  12000.0   20000.0  50000.0  160000.0
Kusum      150.8  18000.0   50000.0  60000.0  110000.0
Kinshuk    200.9  22000.0   70000.0  70000.0  500000.0
Ankit    30000.0  30000.0   10000.0  80000.0  340000.0
Shruti    4000.0  45000.0  125000.0  90000.0  900000.0
Sumeet     196.2  37800.0   52000.0  78438.0   38852.0


In [219]:
#g) Delete the data for the year 2014 from the DataFrame Sales.
sales5 = sales4
sales5 = sales5.drop(columns=2014)
print(sales5)


            2015      2016     2017      2018
Madhu    12000.0   20000.0  50000.0  160000.0
Kusum    18000.0   50000.0  60000.0  110000.0
Kinshuk  22000.0   70000.0  70000.0  500000.0
Ankit    30000.0   10000.0  80000.0  340000.0
Shruti   45000.0  125000.0  90000.0  900000.0
Sumeet   37800.0   52000.0  78438.0   38852.0


In [220]:
# h) Delete the data for sales man Kinshuk from the DataFrame Sales.
sales5 = sales5.drop(['Kinshuk'])
print(sales5)

           2015      2016     2017      2018
Madhu   12000.0   20000.0  50000.0  160000.0
Kusum   18000.0   50000.0  60000.0  110000.0
Ankit   30000.0   10000.0  80000.0  340000.0
Shruti  45000.0  125000.0  90000.0  900000.0
Sumeet  37800.0   52000.0  78438.0   38852.0


In [221]:
#i) Change the name of the salesperson Ankit to Vivaan and Madhu to Shailesh.

sales5 = sales5.rename({'Ankit':'Vivaan', 'Madhu':'Shailesh'})
print(sales5)

             2015      2016     2017      2018
Shailesh  12000.0   20000.0  50000.0  160000.0
Kusum     18000.0   50000.0  60000.0  110000.0
Vivaan    30000.0   10000.0  80000.0  340000.0
Shruti    45000.0  125000.0  90000.0  900000.0
Sumeet    37800.0   52000.0  78438.0   38852.0


In [223]:
# j) Update the sale made by Shailesh in 2018 to 100000.

sales5.loc['Shailesh','2018'] = 100000
print(sales5)

             2015      2016     2017      2018      2018
Shailesh  12000.0   20000.0  50000.0  160000.0  100000.0
Kusum     18000.0   50000.0  60000.0  110000.0       NaN
Vivaan    30000.0   10000.0  80000.0  340000.0       NaN
Shruti    45000.0  125000.0  90000.0  900000.0       NaN
Sumeet    37800.0   52000.0  78438.0   38852.0       NaN


In [165]:
#k) Write the values of DataFrame Sales to a comma separated file SalesFigures.csv on the disk. Do not write the row labels and column labels.

#Exporting
print(sales5)

sales5.to_csv('sales.csv',sep=',', header=True,index=True)

             2015      2016     2017      2018
Shailesh  12000.0   20000.0  50000.0  100000.0
Kusum     18000.0   50000.0  60000.0  110000.0
Vivaan    30000.0  100000.0  80000.0  340000.0
Shruti    60000.0  125000.0  90000.0  900000.0
Sumeet    37800.0   52000.0  78438.0   38852.0


In [166]:
# l) Read the data in the file SalesFigures.csv into a DataFrame SalesRetrieved and Display it. 
# Now update the row labels and column labels of SalesRetrieved to be the same as that of Sales.
#Importing

sales6 = pd.read_csv('sales.csv',sep=',', header=0)

print(sales6)

  Unnamed: 0     2015      2016     2017      2018
0   Shailesh  12000.0   20000.0  50000.0  100000.0
1      Kusum  18000.0   50000.0  60000.0  110000.0
2     Vivaan  30000.0  100000.0  80000.0  340000.0
3     Shruti  60000.0  125000.0  90000.0  900000.0
4     Sumeet  37800.0   52000.0  78438.0   38852.0
