<a href="https://colab.research.google.com/github/jayac251/Machine_Learning/blob/main/panda_basics_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1.2 DataFrames**

Store data in tabular format

| Col1 | Col2 | Col3 |
| --- | --- | --- |
| row1 | row1 | row1 |
| row2 | row2 | row2 |

In [2]:
#creation of empty dataframe
import pandas as pd
import numpy as np

emptyDf = pd.DataFrame()

print(emptyDf)

#creation of dataframes using ndarrays

arr1 = np.array(np.arange(0,9))
arr2 = np.array(np.arange(10,19))
arr3 = np.array(np.arange(20,30))

dFrame1 = pd.DataFrame(arr1)
print('\n\n',dFrame1)

dFrame2 = pd.DataFrame([arr1,arr2,arr3])
print('\n\n',dFrame2)

dFrame2 = pd.DataFrame([arr1,arr2,arr3], columns=['A','B','C','D','E','F','G','H','I','J'])
print('\n\n',dFrame2)

Empty DataFrame
Columns: []
Index: []


    0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8


     0   1   2   3   4   5   6   7   8     9
0   0   1   2   3   4   5   6   7   8   NaN
1  10  11  12  13  14  15  16  17  18   NaN
2  20  21  22  23  24  25  26  27  28  29.0


     A   B   C   D   E   F   G   H   I     J
0   0   1   2   3   4   5   6   7   8   NaN
1  10  11  12  13  14  15  16  17  18   NaN
2  20  21  22  23  24  25  26  27  28  29.0


In [ ]:
#creation of DF from list of Dictionaries

dict1 = [{ 'India':'Virath Kohli','Australia':'Steve Smith','England':'Joe Root'},
         { 'India':'Rohit Sharma','Australia':'Aaron Finch','England':'Ben Stokes'},
         { 'India':'KL Rahul','England':'Craig Overton'}]
print(dict1)

dFrame3 = pd.DataFrame(dict1)
print('\n\n',dFrame3)


[{'India': 'Virath Kohli', 'Australia': 'Steve Smith', 'England': 'Joe Root'}, {'India': 'Rohit Sharma', 'Australia': 'Aaron Finch', 'England': 'Ben Stokes'}, {'India': 'KL Rahul', 'England': 'Craig Overton'}]


           India    Australia        England
0  Virath Kohli  Steve Smith       Joe Root
1  Rohit Sharma  Aaron Finch     Ben Stokes
2      KL Rahul          NaN  Craig Overton


In [ ]:
#creation of DF from Dictionaries of list

dict2 = {'Supraja':['Apple','Banana','Orange'],
         'Girisha':['Grapes','Chikku',np.nan],
         'Ashwin':['Pomogranete',np.nan,np.nan],
         'Adhira':['SweetLime',np.nan,np.nan]}

dFrame4 = pd.DataFrame(dict2)
print('\n\n',dFrame4)

dFrame4 = pd.DataFrame(dict2, columns=['Supraja','Girisha','Adhira','Ashwin'])
print('\n\n',dFrame4)



   Supraja Girisha       Ashwin     Adhira
0   Apple  Grapes  Pomogranete  SweetLime
1  Banana  Chikku          NaN        NaN
2  Orange     NaN          NaN        NaN


   Supraja Girisha     Adhira       Ashwin
0   Apple  Grapes  SweetLime  Pomogranete
1  Banana  Chikku        NaN          NaN
2  Orange     NaN        NaN          NaN


In [ ]:
#creation of DF from series

series1 = pd.Series([10,20,30])
series2 = pd.Series(['Apple','Banana','Cherry'],index=[3,5,1])
dFrame5= pd.DataFrame([series1,series2])
print('\n\n',dFrame5)




       0       1     2      3       5
0  10.0      20  30.0    NaN     NaN
1   NaN  Cherry   NaN  Apple  Banana


In [41]:
#creation of DF from dictionary of Series

dict1 = {'Arun':pd.Series([10,20,30],index=['Maths','Science','Social']),
         'Bala':pd.Series([10,20,30],index=['Maths','Science','Social']),
         'Bala2':pd.Series([10,20,30],index=['Maths','Science','Social']),
         'Chandra':pd.Series([10],index=['Maths'])}
dFrame6= pd.DataFrame(dict1)
print('\n\n',dFrame6)

type(dFrame6.Arun)




          Arun  Bala  Bala2  Chandra
Maths      10    10     10     10.0
Science    20    20     20      NaN
Social     30    30     30      NaN


pandas.core.series.Series

##**Operations on rows and columns in Dataframes**

In [42]:
#Adding new column to DF

dFrame6['Dan'] = 12

dFrame6['Ela'] = [34,56,24]

#update existing column
dFrame6['Ela'] = [34,59,24]

print('\n\n',dFrame6)




          Arun  Bala  Bala2  Chandra  Dan  Ela
Maths      10    10     10     10.0   12   34
Science    20    20     20      NaN   12   59
Social     30    30     30      NaN   12   24


In [43]:
#Adding new row to DF
dFrame6.loc['Tamil'] = [34,54,23,53,44,54]

print('\n\n',dFrame6)

#update existing row
dFrame6.loc['Tamil'] = [34,54,23,53,44,100]
print('\n\n',dFrame6)

dFrame6.loc['CS'] = 0
print('\n\n',dFrame6)




          Arun  Bala  Bala2  Chandra  Dan  Ela
Maths      10    10     10     10.0   12   34
Science    20    20     20      NaN   12   59
Social     30    30     30      NaN   12   24
Tamil      34    54     23     53.0   44   54


          Arun  Bala  Bala2  Chandra  Dan  Ela
Maths      10    10     10     10.0   12   34
Science    20    20     20      NaN   12   59
Social     30    30     30      NaN   12   24
Tamil      34    54     23     53.0   44  100


          Arun  Bala  Bala2  Chandra  Dan  Ela
Maths      10    10     10     10.0   12   34
Science    20    20     20      NaN   12   59
Social     30    30     30      NaN   12   24
Tamil      34    54     23     53.0   44  100
CS          0     0      0      0.0    0    0


#**Deleting rows and columns from DF**

DataFrame.drop()


to delete row, axis = 0

to delete col, axis = 1


In [44]:
#Deleting rows and columns from DF

print('\n\n',dFrame6)

#drop row
dFrame6 = dFrame6.drop('CS',axis=0)
print('\n\n',dFrame6)

#drop col
dFrame6 = dFrame6.drop(['Ela','Dan'],axis=1)
print('\n\n',dFrame6)





          Arun  Bala  Bala2  Chandra  Dan  Ela
Maths      10    10     10     10.0   12   34
Science    20    20     20      NaN   12   59
Social     30    30     30      NaN   12   24
Tamil      34    54     23     53.0   44  100
CS          0     0      0      0.0    0    0


          Arun  Bala  Bala2  Chandra  Dan  Ela
Maths      10    10     10     10.0   12   34
Science    20    20     20      NaN   12   59
Social     30    30     30      NaN   12   24
Tamil      34    54     23     53.0   44  100


          Arun  Bala  Bala2  Chandra
Maths      10    10     10     10.0
Science    20    20     20      NaN
Social     30    30     30      NaN
Tamil      34    54     23     53.0


**Renaming row labels in DF**

In [46]:
#Renaming row labels

print('\n\n',dFrame6)
dFrame6 = dFrame6.rename({'Maths':'Mathematics', 'Social':'Social Science'})
print('\n\n',dFrame6)





                 Arun  Bala  Bala2  Chandra
Mathematics       10    10     10     10.0
Science           20    20     20      NaN
Social Science    30    30     30      NaN
Tamil             34    54     23     53.0


                 Arun  Bala  Bala2  Chandra
Mathematics       10    10     10     10.0
Science           20    20     20      NaN
Social Science    30    30     30      NaN
Tamil             34    54     23     53.0


In [47]:
#Renaming col labels

dFrame6 = dFrame6.rename({ 'Bala2':'Ela'}, axis='columns')
print('\n\n',dFrame6)



                 Arun  Bala  Ela  Chandra
Mathematics       10    10   10     10.0
Science           20    20   20      NaN
Social Science    30    30   30      NaN
Tamil             34    54   23     53.0


## **Accessing DF elements through indexing**



*   Label based indexing
*   Boolean indexing





In [53]:
#Label based indexing
print('\n\n',dFrame6)
print('\n\n')
dFrame6.loc['Science']





                 Arun  Bala  Ela  Chandra
Mathematics       10    10   10     10.0
Science           20    20   20      NaN
Social Science    30    30   30      NaN
Tamil             34    54   23     53.0





Arun       20.0
Bala       20.0
Ela        20.0
Chandra     NaN
Name: Science, dtype: float64

In [61]:
arr7 = np.array(np.arange(1,10))

dFrame7 = pd.DataFrame(arr7)
print(dFrame7,'\n\n\n')

dFrame7.loc[3] # not integer position, it considers as label of index

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9 





0    4
Name: 3, dtype: int64

In [68]:
dFrame6.loc[:,'Arun']

dFrame6['Arun']

Mathematics       10
Science           20
Social Science    30
Tamil             34
Name: Arun, dtype: int64

In [69]:
dFrame6.loc[['Mathematics','Science']]

Arun  Bala  Ela  Chandra
Mathematics    10    10   10     10.0
Science        20    20   20      NaN

In [76]:
#Boolean indexing
print('\n\n',dFrame6,'\n\n\n')
dFrame6.loc['Mathematics']>8

dFrame6['Bala'] > 10



                 Arun  Bala  Ela  Chandra
Mathematics       10    10   10     10.0
Science           20    20   20      NaN
Social Science    30    30   30      NaN
Tamil             34    54   23     53.0 





Mathematics       False
Science            True
Social Science     True
Tamil              True
Name: Bala, dtype: bool

##**Accessing DF elements through slicing**



In [82]:
print('\n\n',dFrame6,'\n\n\n')

print(dFrame6.loc['Mathematics':'Social Science'] ,'\n\n\n')

print(dFrame6.loc['Mathematics':'Social Science','Arun'] ,'\n\n\n')

print(dFrame6.loc['Mathematics':'Social Science','Arun':'Ela'] ,'\n\n\n')

print(dFrame6.loc['Mathematics':'Social Science','Arun':'Ela'] > 10,'\n\n\n')




                 Arun  Bala  Ela  Chandra
Mathematics       10    10   10     10.0
Science           20    20   20      NaN
Social Science    30    30   30      NaN
Tamil             34    54   23     53.0 



                Arun  Bala  Ela  Chandra
Mathematics       10    10   10     10.0
Science           20    20   20      NaN
Social Science    30    30   30      NaN 



Mathematics       10
Science           20
Social Science    30
Name: Arun, dtype: int64 



                Arun  Bala  Ela
Mathematics       10    10   10
Science           20    20   20
Social Science    30    30   30 



                 Arun   Bala    Ela
Mathematics     False  False  False
Science          True   True   True
Social Science   True   True   True 





##**Filtering rows in DataFrames**

In [86]:
# to select or omit particular row(s) , we can use a boolean list specifying True for rows to be shown and 'False' for rows to be omitted.
print('\n\n',dFrame6,'\n\n\n')

print(dFrame6.loc[[True,True,False,False]])




                 Arun  Bala  Ela  Chandra
Mathematics       10    10   10     10.0
Science           20    20   20      NaN
Social Science    30    30   30      NaN
Tamil             34    54   23     53.0 



             Arun  Bala  Ela  Chandra
Mathematics    10    10   10     10.0
Science        20    20   20      NaN


##**Joining, Merging, concatenation of DataFrames**

###**Joining**

In [97]:
#Joining

dict1 = {'Supraja':['Apple','Banana','Orange'],
         'Girisha':['Grapes','Chikku',np.nan],
         'Ashwin':['Pomogranete',np.nan,np.nan],
         'Adhira':['SweetLime',np.nan,np.nan]}

dFrame1 = pd.DataFrame(dict1)
print('\n\n',dFrame1,'\n\n\n')

dict2={'Suresh':['Apple','Lemon','Orange'],
         'Chitra':['Grapes','Chikku','Strawberry']}

dFrame2 = pd.DataFrame(dict2,index=[0,4,5])
print('\n\n',dFrame2,'\n\n\n')


#Join
dFrame1 = dFrame1.append(dFrame2,)
print('\nAfter Append\n',dFrame1,'\n\n\n')

dFrame1 = dFrame1.append(dFrame2,sort = True)

#dFrame1 = dFrame1.append(dFrame2, verify_integrity= True)

dFrame1 = dFrame1.append(dFrame2,ignore_index=True)




   Supraja Girisha       Ashwin     Adhira
0   Apple  Grapes  Pomogranete  SweetLime
1  Banana  Chikku          NaN        NaN
2  Orange     NaN          NaN        NaN 





    Suresh      Chitra
0   Apple      Grapes
4   Lemon      Chikku
5  Orange  Strawberry 




After Append
   Supraja Girisha       Ashwin     Adhira  Suresh      Chitra
0   Apple  Grapes  Pomogranete  SweetLime     NaN         NaN
1  Banana  Chikku          NaN        NaN     NaN         NaN
2  Orange     NaN          NaN        NaN     NaN         NaN
0     NaN     NaN          NaN        NaN   Apple      Grapes
4     NaN     NaN          NaN        NaN   Lemon      Chikku
5     NaN     NaN          NaN        NaN  Orange  Strawberry 





##**Attributes of DataFrame**


In [111]:
ForestArea = {'Assam' :pd.Series([78438, 2797,10192, 15116], index = ['GeoArea', 'VeryDense','ModeratelyDense', 'OpenForest']),
              'Kerala' :pd.Series([ 38852, 1663,9407, 9251], index = ['GeoArea' ,'VeryDense','ModeratelyDense', 'OpenForest']),
              'Delhi' :pd.Series([1483, 6.72, 56.24,129.45], index = ['GeoArea', 'VeryDense','ModeratelyDense', 'OpenForest'])}
ForestAreaDF = pd.DataFrame(ForestArea)
ForestAreaDF

#To display row labels
print('\nDataFrame.index ==>',ForestAreaDF.index)

#to display col labels
print('\nDataFrame.columns ==>',ForestAreaDF.columns)

#to display data type of each col
print('\nDataFrame.dtypes ==>',ForestAreaDF.dtypes)

#to display a numpy ndarray having all values  in the DF without the axis labels
print('\nDataFrame.values ==>',ForestAreaDF.values)

#to display a tuple representing the dimensionality of the dataframe
print('\nDataFrame.shape ==>',ForestAreaDF.shape, ' <== means 4 rows and 3 cols')

print('\nDataFrame.size ==>',ForestAreaDF.size, ' <== means DF has 12 values in it')

# to transpose DF
print('\nDataFrame.T ==>',ForestAreaDF.T)

print('\nDataFrame.head(n) ==>',ForestAreaDF.head(2))
print('\nDataFrame.tail(n) ==>',ForestAreaDF.tail(2))



DataFrame.index ==> Index(['GeoArea', 'VeryDense', 'ModeratelyDense', 'OpenForest'], dtype='object')

DataFrame.columns ==> Index(['Assam', 'Kerala', 'Delhi'], dtype='object')

DataFrame.dtypes ==> Assam       int64
Kerala      int64
Delhi     float64
dtype: object

DataFrame.values ==> [[7.8438e+04 3.8852e+04 1.4830e+03]
 [2.7970e+03 1.6630e+03 6.7200e+00]
 [1.0192e+04 9.4070e+03 5.6240e+01]
 [1.5116e+04 9.2510e+03 1.2945e+02]]

DataFrame.shape ==> (4, 3)  <== means 4 rows and 3 cols

DataFrame.size ==> 12  <== means DF has 12 values in it

DataFrame.T ==>         GeoArea  VeryDense  ModeratelyDense  OpenForest
Assam   78438.0    2797.00         10192.00    15116.00
Kerala  38852.0    1663.00          9407.00     9251.00
Delhi    1483.0       6.72            56.24      129.45

DataFrame.head(n) ==>            Assam  Kerala    Delhi
GeoArea    78438   38852  1483.00
VeryDense   2797    1663     6.72

DataFrame.tail(n) ==>                  Assam  Kerala   Delhi
ModeratelyDense  10192  

##**Importing and Exporting Data between CSV files and DataFrames**

In [113]:
#Exporting
print(ForestAreaDF)

ForestAreaDF.to_csv('ForestArea.csv',sep=',', header=True,index=True)



                 Assam  Kerala    Delhi
GeoArea          78438   38852  1483.00
VeryDense         2797    1663     6.72
ModeratelyDense  10192    9407    56.24
OpenForest       15116    9251   129.45


In [116]:
#Importing

ForestAreaFile = pd.read_csv('ForestArea.csv',sep=',', header=0)

print(ForestAreaFile)

        Unnamed: 0  Assam  Kerala    Delhi
0          GeoArea  78438   38852  1483.00
1        VeryDense   2797    1663     6.72
2  ModeratelyDense  10192    9407    56.24
3       OpenForest  15116    9251   129.45
